



//GET PLANETS
export const GET_PLANETS_SUCCESS = "GET_PLANETS_SUCCESS";
export const GET_PLANETS_REQUEST = "GET_PLANETS_REQUEST";
export const  GET_PLANETS_ERROR = "GET_PLANETS_ERROR";

//GET CHARACTERS
export const GET_CHARACTERS_SUCCESS = "GET_CHARACTERS_SUCCESS";
export const GET_CHARACTERS_ERROR = "GET_CHARACTERS_ERROR";
export const GET_CHARACTERS_REQUEST = "GET_CHARACTERS_REQUEST";

//GET SPACESHIP
export const GET_SPACESHIP_REQUEST = "GET_SPACESHIP_REQUEST";
export const GET_SPACESHIP_SUCCESS = "GET_SPACESHIP_SUCCESS";
export const GET_SPACESHIP_ERROR = "GET_SPACESHIP_ERROR";
